import { ArrowDownRight, ArrowRight, Brain, Check, Clock3, ExternalLink, HeartHandshake, Instagram, MapPin, MessageCircle, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { PublicFooter } from "@/components/PublicFooter";
import { PublicHeader } from "@/components/PublicHeader";

const whatsapp = "https://api.whatsapp.com/send?phone=5546999145645";
const instagram = "https://www.instagram.com/grassiclaudete/";

const specialties = [
  { number: "01", title: "Psicoterapia", text: "Um espaço de escuta para compreender o que você vive e construir novos caminhos com mais clareza." },
  { number: "02", title: "EMDR", text: "Terapia de dessensibilização e reprocessamento para trabalhar traumas, memórias difíceis e bloqueios emocionais." },
  { number: "03", title: "Educação parental", text: "Orientação para relações familiares mais conscientes, respeitosas e conectadas às necessidades das crianças." },
  { number: "04", title: "Atendimento flexível", text: "Consultas on-line e presenciais, com um cuidado pensado para caber na sua rotina e no seu momento." },
];

export default function Home() {
  return <div className="min-h-screen bg-[#fbf8f3] text-[#34251f]">
    <PublicHeader />
    <main>
      <section className="texture overflow-hidden px-5 pb-18 pt-14 sm:pb-26 sm:pt-20">
        <div className="container grid gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center">
          <div className="animate-reveal-up max-w-2xl">
            <div className="mb-8 flex items-center gap-3 text-[10px] font-extrabold uppercase tracking-[.18em] text-[#8b5545]"><span className="h-px w-10 bg-[#c69d87]" /> Psicóloga · CRP 08/22767</div>
            <h1 className="display max-w-2xl text-[clamp(3.5rem,6.5vw,5.7rem)] leading-[.9]">O autoconhecimento é a chave para uma vida <em className="font-normal text-[#7d493a]">saudável.</em></h1>
            <p className="mt-8 max-w-lg text-[15px] leading-7 text-[#6e5d54]">Um espaço seguro para olhar para si com gentileza, compreender suas experiências e encontrar formas mais leves de seguir.</p>
            <div className="mt-9 flex flex-col gap-3 sm:flex-row">
              <a href={whatsapp} target="_blank" rel="noreferrer" className="focus-ring inline-flex h-13 items-center justify-center gap-2 rounded-full bg-[#7d493a] px-6 text-[11px] font-extrabold uppercase tracking-[.1em] text-[#fffaf4] transition hover:bg-[#68392e] active:scale-[.97]">Conversar pelo WhatsApp <MessageCircle size={16} /></a>
              <a href="#sobre" className="focus-ring inline-flex h-13 items-center justify-center gap-2 rounded-full border border-[#cfb8a9] bg-white/50 px-6 text-[11px] font-extrabold uppercase tracking-[.1em] text-[#694d40]">Conhecer meu trabalho <ArrowDownRight size={16} /></a>
            </div>
            <div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-[10px] font-bold uppercase tracking-[.12em] text-[#8b786d]"><span className="inline-flex items-center gap-2"><Check size={13} className="text-[#7d493a]" /> On-line e presencial</span><span className="inline-flex items-center gap-2"><Check size={13} className="text-[#7d493a]" /> Atendimento humanizado</span></div>
          </div>
          <div className="relative mx-auto w-full max-w-[520px] animate-reveal-up [animation-delay:120ms]">
            <div className="absolute -right-4 -top-5 h-28 w-28 rounded-full border border-[#cba893] sm:-right-8 sm:-top-8 sm:h-40 sm:w-40" />
            <div className="relative overflow-hidden rounded-[38px] border-[10px] border-white/70 bg-[#d9c7b7] shadow-[0_30px_80px_rgba(84,54,38,.18)]">
              <div className="relative flex aspect-[.9] flex-col justify-between overflow-hidden bg-[#d9c7b7] p-7 sm:p-10">
                <img src="/media/claudete-profile.jpg" alt="Dra. Claudete Grassi" className="absolute inset-0 h-full w-full object-cover object-center opacity-90 mix-blend-multiply" />
                <div className="absolute inset-0 bg-gradient-to-t from-[#5e4036]/75 via-transparent to-[#f3d9c6]/10" />
                <div className="relative flex items-start justify-between"><span className="grid size-14 place-items-center rounded-full bg-[#fffaf4]/80 text-[#7d493a]"><Brain size={25} strokeWidth={1.4} /></span><span className="rounded-full border border-white/60 bg-white/35 px-3 py-2 text-[9px] font-extrabold uppercase tracking-[.14em] text-[#604e44]">presença & cuidado</span></div>
                <div className="relative h-44 sm:h-56" />
                <div className="rounded-[24px] bg-[#fffaf4]/75 p-5 backdrop-blur-sm"><p className="display text-2xl italic text-[#604e44]">“Você não precisa atravessar tudo sozinha.”</p><p className="mt-3 text-[10px] font-extrabold uppercase tracking-[.15em] text-[#8b5545]">Dr. Claudete Grassi</p></div>
              </div>
            </div>
            <div className="animate-float-soft absolute -bottom-5 -left-5 grid size-24 place-items-center rounded-full border-8 border-[#f7efe7] bg-[#354637] text-center text-[10px] font-extrabold uppercase leading-4 tracking-[.1em] text-[#d3e0ca] shadow-lg">escuta<br />que acolhe</div>
          </div>
        </div>
      </section>

      <section id="sobre" className="bg-white px-5 py-20 sm:py-28">
        <div className="container grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-start">
          <div><p className="text-[10px] font-extrabold uppercase tracking-[.17em] text-[#8b5545]">Sobre o meu trabalho</p><h2 className="display mt-5 max-w-md text-5xl leading-[.95] sm:text-6xl">Cuidar da mente também é um ato de <em className="font-normal text-[#7d493a]">coragem.</em></h2></div>
          <div className="max-w-2xl text-[15px] leading-7 text-[#6e5d54]"><div className="mb-7 grid gap-5 sm:grid-cols-[150px_1fr] sm:items-center"><img src="/media/claudete-emdr.jpg" alt="Dra. Claudete Grassi em atendimento EMDR" className="h-40 w-36 rounded-[24px] object-cover shadow-[0_16px_30px_rgba(84,54,38,.12)]" /><p className="text-xs leading-6 text-[#8b786d]">Imagem pública associada ao perfil profissional. A identidade visual será ajustada com as fotos oficiais aprovadas.</p></div><p>Sou Claudete Grassi, psicóloga, terapeuta de EMDR e educadora parental. Acredito que cada pessoa carrega uma história única — e que o processo terapêutico deve respeitar essa singularidade.</p><p className="mt-5">Meu trabalho é construir, junto com você, um ambiente de confiança para nomear sentimentos, elaborar experiências e descobrir recursos que já existem dentro da sua própria história.</p><div className="mt-8 grid gap-3 sm:grid-cols-3"><div className="rounded-[22px] bg-[#f7efe7] p-5"><HeartHandshake size={20} className="text-[#7d493a]" /><p className="display mt-6 text-2xl text-[#34251f]">Escuta</p><p className="mt-2 text-xs leading-5">Sem julgamentos, com presença.</p></div><div className="rounded-[22px] bg-[#f7efe7] p-5"><Sparkles size={20} className="text-[#7d493a]" /><p className="display mt-6 text-2xl text-[#34251f]">Clareza</p><p className="mt-2 text-xs leading-5">Para entender o que acontece.</p></div><div className="rounded-[22px] bg-[#f7efe7] p-5"><ShieldCheck size={20} className="text-[#7d493a]" /><p className="display mt-6 text-2xl text-[#34251f]">Segurança</p><p className="mt-2 text-xs leading-5">Para avançar no seu ritmo.</p></div></div></div>
        </div>
      </section>

      <section id="na-midia" className="bg-white px-5 pb-20 sm:pb-28"><div className="container rounded-[30px] border border-[#e8d8ca] bg-[#fbf8f3] p-7 sm:p-10"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-[10px] font-extrabold uppercase tracking-[.17em] text-[#8b5545]">Conteúdos e referências</p><h2 className="display mt-3 text-4xl sm:text-5xl">Conversas que ampliam o cuidado.</h2></div><a href="https://www.instagram.com/grassiclaudete/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-[11px] font-extrabold uppercase tracking-[.1em] text-[#7d493a]">Instagram <Instagram size={15} /></a></div><div className="mt-8 grid gap-4 md:grid-cols-2"><a href="https://jornaldebeltrao.com.br/saude/cuidar-da-saude-mental-e-um-presente-para-si/" target="_blank" rel="noreferrer" className="group rounded-[22px] border border-[#eaded2] bg-white p-5 transition hover:-translate-y-1 hover:shadow-[0_18px_40px_rgba(84,54,38,.1)]"><p className="text-[10px] font-extrabold uppercase tracking-[.14em] text-[#8b5545]">Jornal de Beltrão</p><h3 className="display mt-4 text-2xl">Cuidar da saúde mental é um presente para si.</h3><span className="mt-5 inline-flex items-center gap-2 text-[10px] font-extrabold uppercase tracking-[.1em] text-[#7d493a]">Ler matéria <ExternalLink size={13} /></span></a><a href="https://www.estadao.com.br/ciencia/movimentos-oculares-ajudam-a-vencer-trauma/" target="_blank" rel="noreferrer" className="group rounded-[22px] border border-[#eaded2] bg-white p-5 transition hover:-translate-y-1 hover:shadow-[0_18px_40px_rgba(84,54,38,.1)]"><p className="text-[10px] font-extrabold uppercase tracking-[.14em] text-[#8b5545]">Estadão</p><h3 className="display mt-4 text-2xl">Movimentos oculares ajudam a vencer trauma.</h3><span className="mt-5 inline-flex items-center gap-2 text-[10px] font-extrabold uppercase tracking-[.1em] text-[#7d493a]">Ler matéria <ExternalLink size={13} /></span></a></div></div></section>

      <section id="especialidades" className="texture px-5 py-20 sm:py-28"><div className="container"><div className="flex max-w-2xl flex-col gap-4"><p className="text-[10px] font-extrabold uppercase tracking-[.17em] text-[#8b5545]">Como posso ajudar</p><h2 className="display text-5xl leading-[.98] sm:text-6xl">Cuidado psicológico para diferentes fases da vida.</h2><p className="max-w-xl text-[15px] leading-7 text-[#6e5d54]">A terapia começa por uma conversa. A partir dela, encontramos juntos o caminho que faz sentido para você.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{specialties.map((item) => <article key={item.number} className="card-surface group rounded-[26px] border border-white p-6 transition duration-200 hover:-translate-y-1 hover:shadow-[0_24px_50px_rgba(84,54,38,.13)]"><span className="display text-3xl text-[#d0a58f]">{item.number}</span><h3 className="display mt-7 text-2xl leading-tight">{item.title}</h3><p className="mt-3 min-h-24 text-[12px] leading-6 text-[#75645a]">{item.text}</p><div className="mt-6 flex items-center gap-2 border-t border-[#eaded2] pt-4 text-[10px] font-extrabold uppercase tracking-[.1em] text-[#7d493a]">Saiba mais <ArrowRight size={14} /></div></article>)}</div></div></section>

      <section id="como-funciona" className="bg-[#354637] px-5 py-20 text-white sm:py-28"><div className="container grid gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-end"><div><p className="text-[10px] font-extrabold uppercase tracking-[.17em] text-[#d3e0ca]">Um processo possível</p><h2 className="display mt-5 text-5xl leading-[.98] sm:text-6xl">Cuidado também é se sentir <em className="font-normal text-[#d3e0ca]">à vontade.</em></h2><p className="mt-7 max-w-md text-sm leading-7 text-white/60">Você não precisa ter todas as respostas antes de começar. O primeiro passo pode ser apenas uma conversa.</p></div><div className="grid gap-px overflow-hidden rounded-[26px] border border-white/10 bg-white/10 sm:grid-cols-3">{[[MessageCircle,"1. Conversa inicial","Você compartilha o que está vivendo e tira suas dúvidas."],[Clock3,"2. Ritmo possível","Definimos juntos uma frequência que respeite sua rotina."],[Sparkles,"3. Novos caminhos","A terapia se torna um espaço para elaborar e transformar."]].map(([Icon,title,text]) => { const IconComponent = Icon as typeof MessageCircle; return <div key={title as string} className="bg-[#354637] p-6"><IconComponent size={20} className="text-[#d3e0ca]" /><h3 className="display mt-8 text-2xl">{title as string}</h3><p className="mt-3 text-xs leading-6 text-white/55">{text as string}</p></div>; })}</div></div></section>

      <section className="bg-[#f7efe7] px-5 py-16"><div className="container rounded-[30px] border border-[#e8d8ca] bg-white/65 p-8 sm:p-12"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#8b5545]">Atendimento</p><h2 className="display mt-3 text-4xl sm:text-5xl">On-line e presencial em Pato Branco.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-[#75645a]">Os atendimentos são realizados com horário marcado, de segunda a sexta, das 08h às 20h. Sábados e domingos: fechado.</p><div className="mt-5 flex flex-wrap gap-4 text-xs font-bold text-[#604e44]"><span className="inline-flex items-center gap-2"><MapPin size={15} className="text-[#7d493a]" /> Pato Branco · PR</span><span className="inline-flex items-center gap-2"><Clock3 size={15} className="text-[#7d493a]" /> Seg–Sex · 08h–20h</span></div></div><div className="flex flex-col gap-3 sm:flex-row lg:flex-col"><a href={whatsapp} target="_blank" rel="noreferrer" className="focus-ring inline-flex h-12 items-center justify-center gap-2 rounded-full bg-[#7d493a] px-6 text-[11px] font-extrabold uppercase tracking-[.1em] text-[#fffaf4]"><MessageCircle size={15} /> Agendar conversa</a><a href="https://www.google.com/search?q=psicologica+em+pato+branco" target="_blank" rel="noreferrer" className="focus-ring inline-flex h-12 items-center justify-center gap-2 rounded-full border border-[#c8aa98] bg-white/70 px-6 text-[11px] font-extrabold uppercase tracking-[.1em] text-[#694d40]"><ExternalLink size={15} /> Ver avaliações</a></div></div></div></section>

      <section className="bg-white px-5 py-20 sm:py-28"><div className="container grid gap-10 rounded-[34px] bg-[#efe1d4] px-6 py-12 text-center sm:px-12 sm:py-16"><p className="text-[10px] font-extrabold uppercase tracking-[.17em] text-[#8b5545]">Seu momento de cuidado</p><h2 className="display mx-auto max-w-3xl text-5xl leading-[.98] sm:text-6xl">Vamos conversar sobre o que faz sentido para você?</h2><p className="mx-auto max-w-xl text-[15px] leading-7 text-[#6e5d54]">Se sentir que é hora de olhar para si com mais carinho, me escreva. Será um prazer acolher sua mensagem.</p><div className="mt-2 flex flex-col justify-center gap-3 sm:flex-row"><a href={whatsapp} target="_blank" rel="noreferrer" className="focus-ring inline-flex h-13 items-center justify-center gap-2 rounded-full bg-[#7d493a] px-6 text-[11px] font-extrabold uppercase tracking-[.1em] text-[#fffaf4]">Falar no WhatsApp <MessageCircle size={16} /></a><a href={instagram} target="_blank" rel="noreferrer" className="focus-ring inline-flex h-13 items-center justify-center gap-2 rounded-full border border-[#c8aa98] bg-white/70 px-6 text-[11px] font-extrabold uppercase tracking-[.1em] text-[#694d40]"><Instagram size={16} /> Instagram</a></div></div></section>
    </main>
    <PublicFooter />
  </div>;
}
